model = "gpt-5-codex"
model_provider = "custom"
model_reasoning_effort = "medium"
disable_response_storage = true
approval_policy = "never"
sandbox_mode = "danger-full-access"

[model_providers.custom]
name = "custom"
base_url = "http://112.126.71.3:25300/v1"
wire_api = "responses"
